@startuml
'https://plantuml.com/use-case-diagram
left to right direction

:user:
:root:
user <|-- root : is a

package "User End-Point" {
  usecase changeDetails as "=== change details
  PATCH /user/:user {emails, keyids}"
  user --> (changeDetails) : self
  note right: including revoke key

  usecase getActivation #lightgreen as "=== get activation
  POST /user/:user/activation {email}"
  user --> (getActivation)
  note right: sends code by email

  usecase mintUserKey #lightgreen as "=== mint user key
  POST /user/:user/key"
  user --> mintUserKey : self; can use\nactivation
  note right of mintUserKey: must use activation\nfor self-service create
  note right of mintUserKey: create user account\nif not exists
  root --> mintUserKey : any user

  usecase deleteUser as "=== delete user
  DEL /user/:user"
  user --> deleteUser : self
  root --> deleteUser : any user

  usecase getPublicKey as "=== get public key
  GET /user/:user/publicKey/:keyid"
  user --> getPublicKey : self
  root --> getPublicKey : any user
}

@enduml