@startuml
'https://plantuml.com/sequence-diagram
!pragma teoz true
hide footbox

title: Basic Write

participant Gateway as gw
participant "App" as app

activate app
app -> gw ++: POST \~/state?lock { ... }
gw -> gw: enqueue Update 1
'Note that other operations on the domain can happen independently
return 201 Created ETag: "1" Location: \~/state?lock {Update 1}
& <- gw: Operation 1 <<publish>>
app -> app: process\nUpdate 1
app -> gw ++: DELETE \~/state?lock If-Match: "1"
note left
Lock deletion is //not//
like ACID commit –
operation has already
been sent
end note
gw -> gw: dequeue Update 1
return 200 OK
deactivate app

@enduml