@startuml
'https://plantuml.com/sequence-diagram
hide footbox

title App with Gateway account

participant "App\nClient" as client
participant "Identity Provider" as idp
participant "App Service\nor lambda" as service

client <--> idp: Authenticate user (or anon)
client -> service ++ : get config for subdomain {userId}
service -> Gateway ++: PUT /domain/<<account>>/<<name>>\n{authKey, userId}
Gateway -> Gateway: Create user JWT,\nsign with authKey
return config for new clones
note left
<code>
{
  @domain:"<<name>>.<<account>>.<<hostname>>",
  genesis:true,
  io: { auth: { jwt } }
}
</code>
end note
note right
if backup clone
or domain exists,
genesis is false
end note
return config
client -> client ++: Create clone
client <--> Gateway: socket.io remotes ""{jwt}""

@enduml