# fly.toml app configuration file generated for m-ld-gateway on 2023-07-19T08:18:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "m-ld-gateway"
primary_region = "lhr"

[mounts]
  source="gateway_data"
  destination="/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
