###

POST {{gateway}}/api/v1/user/{{account}}/activation
Accept: application/json
Content-Type: application/json

{ "email": "{{email}}" }

###

POST {{gateway}}/api/v1/user/{{account}}/key
Authorization: Bearer {{jwe}}
X-Activation-Code: {{activation}}
Accept: application/json

###

POST {{gateway}}/api/v1/user/{{account}}/key
Authorization: Basic {{rootAccount}} {{rootKey}}
Accept: application/json

###

PATCH {{gateway}}/api/v1/user/{{account}}
Authorization: Basic {{account}} {{accountKey}}
Accept: application/json
Content-Type: application/json

{ "@insert": { "remotesAuth": "{{remotesAuth}}" } }

###