###

PATCH {{gateway}}/api/v1/user/{{account}}
Authorization: Basic {{account}} {{accountKey}}
Content-Type: application/json

{ "@insert": { "naming": "uuid" } }

###

POST {{gateway}}/api/v1/domain/{{account}}
Accept: application/json

###