@startuml
'https://plantuml.com/sequence-diagram
!pragma teoz true
hide footbox

participant Gateway as gw
participant "App" as app

activate app
app -> gw ++: POST /init/≪acc≫/domain/≪dn≫
note right
?user=..
&subscribe=≪webhook≫
authorisation=..
end note
gw -> gw: create/rev-up clone
return 200 OK
note left
{
  config,
  state: 1,
  updates: []
  subsId: ≪guid≫
}
end note
app -> app: process updates
loop
app -> gw ++: GET /state/1?query={...}
return 200 OK: //chunked subjects//
end loop
app -> gw ++: DELETE /state/1/lock
return 200 OK
deactivate app

...interactions e.g. ←GET, ←POST, POST→...
app -> gw: DELETE /subs/≪guid≫

@enduml