@startuml
'https://plantuml.com/sequence-diagram
!pragma teoz true
hide footbox

participant Gateway as gw
box App
participant "(thread 1)" as app
participant "(thread 2)" as app2
end box

group POST to state with pending [happy]
-> gw ++: Operation 1
gw -> app2 ++--: POST /webhook?state=1
note over app2: Update being\nprocessed
activate app
app -> gw ++: POST /state/0 { ... }
return 404 Not Found\n(Update 1 is pending)
deactivate app
deactivate app2
end group

group POST to wildcard state [happy]
-> gw ++: Operation 1
gw -> app2 ++--: POST /webhook?state=1
note over app2: Update being\nprocessed
activate app
app -> gw ++: POST /state { ... }
note over gw
write is delayed
by pending Update
end note
app2 -> gw ++: GET /updates
return 200 OK: Update 1
app2 -> gw ++: DELETE /state/1/lock
return 200 OK
deactivate app2
gw --> app: 200 OK: Update 2\n//or// 408 Request Timeout
deactivate gw
app -> gw ++: DELETE /state/2/lock
return 200 OK
deactivate app
end group

@enduml