@startuml
'https://plantuml.com/sequence-diagram
!pragma teoz true
hide footbox

title: Concurrent Write and Update

participant Gateway as gw
box App
participant "(thread 1)" as app
participant "(thread 2)" as app2
end box

group write to expected tick
-> gw ++: Operation 1
gw -> app2 ++--: POST /webhook?ETag="1"&Location=\~/state?lock [Update 1]
app2 -> app2: process\nUpdate 1
activate app
& app -> gw ++: POST \~/state If-Match: "0" { ... }
return 412 Precondition Failed\n(Update 1 is pending)
deactivate app
deactivate app2
end group

group write to wildcard tick
-> gw ++: Operation 1
gw -> app2 ++--: POST /webhook?ETag="1"&Location=\~/state?lock [Update 1]
app2 -> app2: process\nUpdate 1
activate app
& app -> gw ++: POST \~/state?lock { ... }
note over gw
write is delayed
by pending lock
end note
app2 -> gw ++: DELETE \~/state?lock If-Match: "1"
return 200 OK
deactivate app2
gw --> app: 201 Created ETag: "2" Location: \~/state?lock {Update 2}\n//or// 408 Request Timeout
deactivate gw
app -> app: process\nUpdate 2
app -> gw ++: DELETE \~/state?lock If-Match: "2"
return 200 OK
deactivate app
end group

@enduml