@startuml
'https://plantuml.com/sequence-diagram
!pragma teoz true
hide footbox

participant Gateway as gw
participant "App" as app

group operation [happy]
-> gw ++: Operation 1
gw -> gw: apply Operation 1
gw -> gw: enqueue Update 1
gw -> app ++--: MESSAGE Update 1
app -> app: process Update 1
app -> gw ++: ACK 1
gw -> gw: dequeue Update 1
return RECEIPT
deactivate app
end group

group write [happy]
activate app
app -> gw ++: SEND 1 { ... }
gw -> gw: enqueue Update 1
gw --> app: RECEIPT 1
note right
receipt cannot
have a body –
must wait for
update message
end note
return MESSAGE Update 1
& <- gw: Operation 1
app -> app: process Update 1
app -> gw ++: ACK 1
note left
Ack is //not// like
ACID commit –
operation is
already sent
end note
gw -> gw: dequeue Update 1
return RECEIPT
deactivate app
end group

note across
Using STOMP, correlations are
manual, even for writes
end note

@enduml